title: Mi primer blog
author: SombraN
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  En este momento nos encontramos profundizando sobre las páginas GitHug, en específico,
  añadiendo un tema.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
